language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-user .
  - docker tag udagram-api-user festus971/udagram-api-user:latest
  - docker build -t udagram-api-feed .
  - docker tag udagram-api-feed festus971/udagram-api-feed:latest
  - docker build -t udagram-frontend .
  - docker tag udagram-frontend festus971/udagram-frontend:latest
  - docker build -t reverse-proxy .
  - docker tag reverse-proxy festus971/reverse-proxy:latest

# Tasks to perform after the process is successful. Formatting the Docker username and password as below enables you to programmatically log in without having the password exposed in logs.
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push festus971/udagram-api-user:latest
  - docker push festus971/udagram-api-feed:latest
  - docker push festus971/udagram-frontend:latest
  - docker push festus971/reverse-proxy:latest

env:
  global:
    - secure: <encrypted-docker-username>
    - secure: <encrypted-docker-password>
